Prog4Homework/Formula1.Web/Models/Pilot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Formula1.Web.Models
{
    public class Pilot
    {
        [Display(Name = "Pilot ID")]
        [Required]
        public int ID { get; set; }

        [Display(Name = "Pilot Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Pilot Birth")]
        [Required]
        public int Birth { get; set; }

        [Display(Name = "Pilot Points")]
        [Required]
        public int Points { get; set; }

        [Display(Name = "Pilot Races Won")]
        [Required]
        public int RacesWon { get; set; }

        [Display(Name = "Pilot Nationality")]
        [Required]
        public string Nationality { get; set; }

        [Display(Name = "Pilot Team")]
        public string Team { get; set; }
    }
}

Prog4Homework/Formula1.Web/Models/PilotViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Formula1.Web.Models
{
    public class PilotViewModel
    {
        public Pilot EditedPilot { get; set; }
        public List<Pilot> ListOfPilots { get; set; }
    }
}

Prog4Homework/Formula1.Web/Controllers/PilotController.cs
using AutoMapper;
using Formula1.Data;
using Formula1.Logic;
using Formula1.Repository;
using Formula1.Web.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Formula1.Web.Controllers
{
    public class PilotController : Controller
    {
        IPilotLogic logic;
        IMapper mapper;
        PilotViewModel vm;
        public PilotController()
        {
            PilotRepository pilotRepo = new PilotRepository();
            logic = new PilotLogic(pilotRepo);
            mapper = MapperFactory.CreateMapper();

            vm = new PilotViewModel();
            vm.EditedPilot = new Pilot();
            var pilots = logic.GetAllPilotsAsPilots().ToList();
            vm.ListOfPilots = mapper.Map<IList<Data.Pilots>, List<Models.Pilot>>(pilots);
        }

        private Pilot GetPilotModel(int id)
        {
            Pilots onePilot = logic.GetOnePilotAsPilot(id);
            return mapper.Map<Data.Pilots, Models.Pilot>(onePilot);
        }

        // GET: Pilot
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("PilotIndex", vm);
        }

        // GET: Pilot/Details/5
        public ActionResult Details(int id)
        {
            return View("PilotDetails", GetPilotModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.RemovePilot(id))
                TempData["editResult"] = "DELETE OK";
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedPilot = GetPilotModel(id);
            return View("PilotIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Pilot pilot, string editAction)
        {
            if(ModelState.IsValid && pilot != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    DateTime.TryParseExact(pilot.Birth.ToString(), "yyyy", CultureInfo.CurrentCulture, DateTimeStyles.None, out DateTime birth);
                    Pilots p = new Pilots
                    {
                        pilot_id = pilot.ID,
                        pilot_name = pilot.Name,
                        pilot_birth = birth,
                        pilot_points = pilot.Points,
                        pilot_racesWon = pilot.RacesWon,
                        pilot_nationality = pilot.Nationality,
                        pilot_team = null
                    };
                    logic.CreateOnePilot(p);
                }
                else
                {
                    DateTime.TryParseExact(pilot.Birth.ToString(), "yyyy", CultureInfo.CurrentCulture, DateTimeStyles.None, out DateTime birth);
                    Pilots p = new Pilots
                    {
                        pilot_id = pilot.ID,
                        pilot_name = pilot.Name,
                        pilot_birth = birth,
                        pilot_points = pilot.Points,
                        pilot_racesWon = pilot.RacesWon,
                        pilot_nationality = pilot.Nationality,
                        pilot_team = null
                    };
                    bool success = logic.UpdatePilotAsPilot(pilot.ID, p);
                    if (!success) TempData["editResult"] = "Edit FAIL";
                }
                return RedirectToAction(nameof(Index));
            }
            else 
            {
                ViewData["editAction"] = "Edit";
                vm.EditedPilot = pilot;
                return View("PilotIndex", vm);
            }
        }
    }
}

Prog4Homework/Formula1.Web/Views/Pilot/PilotDetails.cshtml
@model Formula1.Web.Models.Pilot
@{
    ViewBag.Title = "PilotDetails";
}

<h2>Datasheet of one pilot</h2>
@Html.ActionLink("Back to the list", "Index");

<table>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Birth)</td>
        <td>@Html.DisplayFor(m => m.Birth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nationality)</td>
        <td>@Html.DisplayFor(m => m.Nationality)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Points)</td>
        <td>@Html.DisplayFor(m => m.Points)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.RacesWon)</td>
        <td>@Html.DisplayFor(m => m.RacesWon)</td>
    </tr>
</table>

Prog4Homework/Formula1.Web/Views/Pilot/PilotEdit.cshtml
@model Formula1.Web.Models.Pilot

<h2>Edit one pilot</h2>

@using (Html.BeginForm("Edit", "Pilot"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    //@Html.HiddenFor(m => m.ID)
    //@Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.ID)</div>
    <div class="editor-field">@Html.EditorFor(m => m.ID)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Birth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Birth)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Nationality)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nationality)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Points)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Points)</div>

    <div class="editor-label">@Html.LabelFor(m => m.RacesWon)</div>
    <div class="editor-field">@Html.EditorFor(m => m.RacesWon)</div>

    <input type="submit" value="SEND" />
}

Prog4Homework/Formula1.Web/Views/Pilot/PilotIndex.cshtml
@model Formula1.Web.Models.PilotViewModel

@{
    ViewBag.Title = "PilotIndex";
}

<h2>Pilot Index</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("PilotEdit", Model.EditedPilot)
@Html.Partial("PilotList", Model.ListOfPilots)

Prog4Homework/Formula1.Web/Views/Pilot/PilotList.cshtml
@model IEnumerable<Formula1.Web.Models.Pilot>

<h2>List of pilots</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(m => m.First().ID) </th>
        <th>@Html.DisplayNameFor(m => m.First().Name) </th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Edit</th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(m => item.ID) </td>
            <td>@Html.DisplayFor(m => item.Name) </td>
            <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ID })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
        </tr>
    }
</table>
}